[2025-07-30T11:11:53.937+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T11:11:54.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_pipeline.load_data_to_postgres manual__2025-07-30T11:11:47.518903+00:00 [queued]>
[2025-07-30T11:11:54.077+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_pipeline.load_data_to_postgres manual__2025-07-30T11:11:47.518903+00:00 [queued]>
[2025-07-30T11:11:54.079+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-30T11:11:54.424+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2025-07-30 11:11:47.518903+00:00
[2025-07-30T11:11:54.447+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_pipeline', 'load_data_to_postgres', 'manual__2025-07-30T11:11:47.518903+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmp0g0cjsn_']
[2025-07-30T11:11:54.454+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=565) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-30T11:11:54.455+0000] {standard_task_runner.py:91} INFO - Job 239: Subtask load_data_to_postgres
[2025-07-30T11:11:54.456+0000] {standard_task_runner.py:63} INFO - Started process 567 to run task
[2025-07-30T11:11:54.594+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_pipeline.load_data_to_postgres manual__2025-07-30T11:11:47.518903+00:00 [running]> on host 9c353dd7cf4b
[2025-07-30T11:11:54.718+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T11:11:47.518903+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T11:11:47.518903+00:00'
[2025-07-30T11:11:54.719+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T11:11:54.768+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-30T11:11:54.770+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T11:11:54.782+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=financial_etl_pipeline, task_id=load_data_to_postgres, execution_date=20250730T111147, start_date=20250730T111154, end_date=20250730T111154
[2025-07-30T11:11:54.837+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-30T11:11:54.860+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-30T11:11:54.864+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
