[2025-07-28T12:43:43.455+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-28T12:43:43.738+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: financial_etl_dag.load_data manual__2025-07-28T12:43:36.590512+00:00 [queued]>
[2025-07-28T12:43:43.747+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: financial_etl_dag.load_data manual__2025-07-28T12:43:36.590512+00:00 [queued]>
[2025-07-28T12:43:43.749+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-28T12:43:43.763+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-28 12:43:36.590512+00:00
[2025-07-28T12:43:43.784+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=327) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-28T12:43:43.780+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'financial_etl_dag', 'load_data', 'manual__2025-07-28T12:43:36.590512+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/financial_etl_dag.py', '--cfg-path', '/tmp/tmpm7fov4b5']
[2025-07-28T12:43:43.785+0000] {standard_task_runner.py:63} INFO - Started process 329 to run task
[2025-07-28T12:43:43.785+0000] {standard_task_runner.py:91} INFO - Job 102: Subtask load_data
[2025-07-28T12:43:43.887+0000] {task_command.py:426} INFO - Running <TaskInstance: financial_etl_dag.load_data manual__2025-07-28T12:43:36.590512+00:00 [running]> on host 3fd530ef422e
[2025-07-28T12:43:44.004+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='financial_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T12:43:36.590512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-28T12:43:36.590512+00:00'
[2025-07-28T12:43:44.005+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-28T12:43:44.054+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-28T12:43:44.061+0000] {base.py:84} INFO - Using connection ID '***_db' for task execution.
[2025-07-28T12:43:44.067+0000] {sql.py:457} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS transactions (
        transaction_id INT,
        user_id INT,
        amount FLOAT,
        currency VARCHAR(10),
        timestamp TIMESTAMP,
        merchant VARCHAR(50),
        fraud_flag BOOLEAN
    );
    , parameters: None
[2025-07-28T12:43:44.073+0000] {logging_mixin.py:188} INFO - [LOAD] Ensured transactions table exists
[2025-07-28T12:43:44.103+0000] {logging_mixin.py:188} INFO - [LOAD] Inserted 3 rows into 'transactions'
[2025-07-28T12:43:44.104+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-28T12:43:44.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-28T12:43:44.114+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=financial_etl_dag, task_id=load_data, execution_date=20250728T124336, start_date=20250728T124343, end_date=20250728T124344
[2025-07-28T12:43:44.161+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-28T12:43:44.173+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-07-28T12:43:44.185+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-28T12:43:44.190+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
